'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n-1)/2    1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n-1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

import math
import time
import profile


def is_square_number(n):
    square = int(math.sqrt(n))
    return n == square**2


def main():
    start = time.time()
    print __doc__

    for i in xrange(1, 30000):
        hn = i*(2*i-1)
        if is_square_number(1+8*hn) and is_square_number(1+24*hn) and (1+int(math.sqrt(1+8*hn)))%2 == 0 and (1+int(math.sqrt(1+24*hn)))%6==0:
            print i, hn

    print "It costs:", time.time() - start, "seconds"

if __name__ == "__main__":
    profile.run("main()")
